bitlbee:
  image: 'vanityshed/bitlbee-alpine-plugins:latest'
  restart: always

  ports:
    - '6667:6667'
  volumes:
    - '/opt/dockerdata/bitlbee:/bitlbee-data'
    - '/etc/localtime:/etc/localtime:ro'
